const COLORS = {
  color1  : "#0A0A11",
  color2  : "#161F37",
  color3  : "#F3F3F3",
  color4  : "#4070cd",
  color5  : "#434D67",
  color6  : "#FAFAFA",
  color7  : "rgba(243, 243, 243, 0.5)",
  color8  : "rgba(243, 243, 243, 0.4)",
  color9  : "rgba(243, 243, 243, 0.2)",
  color10 : "rgba(22, 31, 55, 0.5)",  
  color11 : "#DA1414",  
  color12 : "transparent",
  color13 : "#050E24",
  color14 : "rgba(10, 10, 17, 0.5)", 
  color15 : "rgba(22, 31, 55, 0.1)", 
  color16 : "rgba(22, 31, 55, 0.2)", 
  color17 : "#3CBC81",
  color18 : "rgba(10, 10, 17, 0.2)", 
  color19 : "rgba(10, 10, 17, 0.4)", 
  color20 : "#FFFFFF",
  color21 : "#4070CD",
  color22 : "rgba(243, 243, 243, 0.3)",
  color23 : "#11100a", 
  color24 : "rgb(170, 170, 170)", 
  color25 : "rgba(243, 243, 243, 0.8)",
  color26 : "#3CBC81",
  color27 : "rgba(243, 243, 243, 0.65)",
  color28 : "rgba(64, 112, 205, 0.5)",
  color29 : "rgba(22, 31, 55, 0.9)",  
}

export const DARK_THEME = {
  mainBackground: COLORS.color1,
  secondaryBackground: COLORS.color3,
  mainTextColor: COLORS.color3,
  welcomepagetextColor: COLORS.color6,
  authButtonColor: COLORS.color3,
  authButtonBackColorHover: COLORS.color2,
  authButtonBorderColor: COLORS.color9,
  backGroundBtnColor: COLORS.color3,
  backGroundBtnColorHover: COLORS.color3,
  backGroundBtnColorActive: COLORS.color5,
  borderBtnColor: COLORS.color12,
  borderBtnColorHover: COLORS.color4,
  borderBtnColorActive: COLORS.color9,
  btnColorActive: COLORS.color9,
  seeMoreBtnTextColor : COLORS.color7,
  borderHeaderColor : COLORS.color9,
  navTextColor : COLORS.color3,
  navBorderColor : COLORS.color9,
  navTextColorHover : COLORS.color3,
  navBackgroundColor : COLORS.color12,
  navBackgroundColorHover : COLORS.color2,
  themeSwitcherColor : COLORS.color2,
  themeSwitcherBackgroundColor : COLORS.color3,
  footerTextColor : COLORS.color3,
  footerTermsColor : COLORS.color7,
  footerBackgroundColor : COLORS.color1,
  footerLinkBorderColor : COLORS.color9,
  footerLinkBorderColorHover : COLORS.color7,
  footerLinkTextColor : COLORS.color25,
  footerLinkTextColorHover : COLORS.color3,
  formErrorMsgColor: COLORS.color11,
  formSuccessMsgColor: COLORS.color17,
  filterDrinksBorderColor: COLORS.color9,
  filterDrinksBorderColorHover: COLORS.color7,
  selectMenuBackground : COLORS.color2,
  selectInputColor: COLORS.color3,
  selectOptionColor: COLORS.color8,
  selectOptionColor_focused: COLORS.color3,
  selectScrollbarThumbColor: COLORS.color5,
  selectdropdownIndicatorColor: COLORS.color5,
  selectDropdownIndicatorColorHover: COLORS.color7,
  selectMenuBackground: COLORS.color2,
  paginationSelectedColor: COLORS.color4,
  paginationLabels: COLORS.color22,
  paginationLabelsHover: COLORS.color3,
  trashBucketBackgroundHover: COLORS.color5,
  imageBackground : COLORS.color2,
  imageBackgroundHover: COLORS.color10,
  inputLabelColordHasValue : COLORS.color26,
  inputLabelColorNoValue : COLORS.color7,
  scrollUpBtnColor: COLORS.color14,
  scrollUpBtnColorHover: COLORS.color2,
  addImgBackground: COLORS.color3,
  addImgBackgroundHover: COLORS.color28,
  addImgSvgColor: COLORS.color1,
  addImgSvgColorHover: COLORS.color3,
};



export const LIGHT_THEME = {
  mainBackground: COLORS.color3,
  secondaryBackground: COLORS.color2,
  mainTextColor: COLORS.color1,
  welcomepagetextColor: COLORS.color6,
  authButtonColor: COLORS.color3,
  authButtonBackColorHover: COLORS.color2,
  authButtonBorderColor: COLORS.color9,
  backGroundBtnColor: COLORS.color2,
  backGroundBtnColorHover: COLORS.color13,
  backGroundBtnColorActive: COLORS.color5,
  borderBtnColor: COLORS.color12,
  borderBtnColorHover: COLORS.color14,
  borderBtnColorActive: COLORS.color9,
  btnColorActive: COLORS.color9,
  seeMoreBtnTextColor : COLORS.color14,
  borderHeaderColor : COLORS.color15,
  navTextColor : COLORS.color2,
  navTextColorHover : COLORS.color3,
  navBorderColor : COLORS.color16,
  navBackgroundColor : COLORS.color12,
  navBackgroundColorHover : COLORS.color2,
  themeSwitcherColor : COLORS.color3,
  themeSwitcherBackgroundColor : COLORS.color2,
  footerTextColor : COLORS.color3,
  footerTermsColor : COLORS.color7,
  footerBackgroundColor : COLORS.color1,
  footerLinkBorderColor : COLORS.color9,
  footerLinkBorderColorHover : COLORS.color7,
  footerLinkTextColor : COLORS.color25,
  footerLinkTextColorHover : COLORS.color3,
  formErrorMsgColor: COLORS.color11,
  formSuccessMsgColor: COLORS.color17,
  filterDrinksBorderColor: COLORS.color18,
  filterDrinksBorderColorHover: COLORS.color14,
  selectMenuBackground : COLORS.color20,
  selectInputColor: COLORS.color3,
  selectOptionColor: COLORS.color19,
  selectOptionColor_focused: COLORS.color1,
  selectScrollbarThumbColor: COLORS.color3,
  selectDropdownIndicatorColor: COLORS.color3,
  selectDropdownIndicatorColorHover: COLORS.color7,
  selectMenuBackground: COLORS.color20,
  paginationSelectedColor: COLORS.color21,
  paginationLabels: COLORS.color23,
  paginationLabelsHover: COLORS.color1,
  trashBucketBackgroundHover: COLORS.color5,
  imageBackground : COLORS.color2,
  imageBackgroundHover: COLORS.color29,
  inputLabelColordHasValue : COLORS.color26,
  inputLabelColorNoValue : COLORS.color14,
  scrollUpBtnColor: COLORS.color27,
  scrollUpBtnColorHover: COLORS.color3,
  addImgBackground: COLORS.color3,
  addImgBackgroundHover: COLORS.color28,
  addImgSvgColor: COLORS.color1,
  addImgSvgColorHover: COLORS.color3,
};